name: dart_server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: Wai Xiong <waixiong1997@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: ^1.5.0
  shelf: ^0.7.5
  shelf_static: ^0.2.8
  shelf_router: ^0.7.2
  http_server: ^0.9.8+3
  mime: ^0.9.6+3
  image: ^2.1.4

dev_dependencies:
  pedantic: ^1.8.0
